<div class="lesson-chat" data-tai-chat data-actor="{{ $actorId }}" data-lesson="{{ $lesson->lessonId }}" data-question="{{ is_string(request()->query('question_id')) ? request()->query('question_id') : '' }}" data-attempt="{{ is_string(request()->query('attempt_id')) ? request()->query('attempt_id') : '' }}" data-api="{{ url('/ai-tutor/api/v1') }}">
    <template data-chat-avatar="tutor">@include('ai-tutor::partials.avatar', ['avatarRole' => 'tutor'])</template>
    <template data-chat-avatar="learner">@include('ai-tutor::partials.avatar', ['avatarRole' => 'learner'])</template>
    <header class="lesson-chat-header">@include('ai-tutor::partials.avatar', ['avatarRole' => 'tutor'])<div><h2>Gia sư tiếng Anh AI</h2><p><i></i> Cùng bạn hiểu bài hơn mỗi ngày</p></div></header>
    <div class="lesson-chat-toolbar"><span class="lesson-credit" data-credit-balance>{{ $creditLabel }}</span>@include('ai-tutor::partials.learning-theme-toggle')<details><summary aria-label="Tùy chọn hội thoại">@include('ai-tutor::partials.icon', ['name' => 'more', 'size' => 20])</summary><div><button type="button" data-reload>Tải lại hội thoại</button><button type="button" data-new-conversation>Hội thoại mới</button><button type="button" data-export>Xuất hội thoại</button><button type="button" data-delete>Xóa hội thoại</button></div></details></div>
    <div class="lesson-chat-mode"><label for="lesson-tutor-mode">Cách hướng dẫn</label><select id="lesson-tutor-mode" data-mode><option value="hints_first">Gợi ý trước</option><option value="explain">Giải thích</option><option value="socratic">Hỏi gợi mở</option><option value="practice">Luyện tập</option><option value="review">Ôn tập</option><option value="exam">Bài thi — không hỗ trợ đáp án</option></select></div>
    <section class="lesson-chat-history" data-history aria-label="Hội thoại" role="log" aria-live="polite"><div class="lesson-chat-welcome">@include('ai-tutor::partials.avatar', ['avatarRole' => 'tutor'])<h3>Chào bạn, mình là gia sư AI!</h3><p>Bạn muốn hiểu rõ phần nào trong bài? Hãy đặt câu hỏi hoặc chọn một gợi ý bên dưới.</p></div></section>
    <div class="lesson-chat-prompts"><button type="button" data-quick-prompt="Hãy giải thích dễ hiểu hơn nội dung chính của bài học này.">Giải thích dễ hơn</button><button type="button" data-quick-prompt="Hãy cho thêm ví dụ tiếng Anh kèm giải thích tiếng Việt cho nội dung bài học này.">Cho thêm ví dụ</button><button type="button" data-quick-prompt="Hãy giúp tôi luyện 5 câu về nội dung bài học này, hỏi từng câu và chờ tôi trả lời.">Luyện 5 câu</button></div>
    <p class="lesson-chat-status" role="status" data-status>Sẵn sàng hỗ trợ bài học của bạn.</p>
    <p><span data-lesson-label>{{ is_string(request()->query('question_id')) ? 'Câu hỏi '.request()->query('question_id') : 'Bài học '.$lesson->lessonId }}</span> <button type="button" data-lesson-context>Hỏi về bài học</button></p>
    <button type="button" data-next-hint disabled>Xin gợi ý tiếp theo</button>
    <form class="lesson-chat-compose" data-chat-form><label class="sr-only" for="lesson-tutor-message">Câu hỏi cho gia sư</label><textarea id="lesson-tutor-message" name="message" rows="2" maxlength="4000" placeholder="Hỏi về bài học…" required></textarea><button type="submit" aria-label="Gửi câu hỏi">@include('ai-tutor::partials.icon', ['name' => 'send', 'size' => 22])</button><button type="button" data-retry hidden>Thử lại cùng yêu cầu</button></form>
    <p class="lesson-chat-footnote">AI có thể nhầm lẫn. Hãy đối chiếu với nội dung bài học.</p>
</div>
