// Browser test uses the isolated mock server only. No host auth, DB or provider.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const { chromium } = await import(process.env.AI_PREVIEW_PLAYWRIGHT_MODULE ?? 'playwright');
const origin = 'http://127.0.0.1:' + (process.argv[2] ?? '9013');
const browser = await chromium.launch({ executablePath: process.env.AI_PREVIEW_CHROME, headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage(); const errors = []; const posts = [];
page.on('pageerror', error => errors.push(error.message));
page.on('dialog', dialog => { if (dialog.type() !== 'beforeunload') errors.push('Unexpected browser dialog: ' + dialog.type()); dialog.accept(); });
page.on('request', req => { if (req.method() === 'POST' && /\/(submit|retry)$/.test(req.url())) posts.push(req.postDataJSON()); });
const editor = page.locator('[data-writing-editor]');
async function waitText(selector, text) {
    for (let attempt = 0; attempt < 100; attempt++) {
        if ((await page.locator(selector).textContent())?.includes(text)) return;
        await new Promise(resolve => setTimeout(resolve, 100));
    }
    assert.fail(`Timed out waiting for ${selector}: ${text}`);
}
const saved = async () => {
    await waitText('[data-writing-save]', 'Đã tự động lưu lúc');
    assert.match(await page.locator('[data-writing-save]').textContent(), /^Đã tự động lưu lúc \d{2}:\d{2}$/);
};
try {
    await page.goto(origin + '/writing');
    await page.locator('[data-writing-start]').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-writing-workspace]').isVisible(), true);
    assert.equal(await page.locator('.tai-writing-results').isVisible(), true);
    assert.equal((await editor.getAttribute('aria-disabled')) === 'true', true);
    assert.equal(await page.locator('[data-writing-submit]').isDisabled(), true);
    assert.equal(await page.locator('[data-writing-credit]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-scoreboard]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-export]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-tabs]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-guide]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-controls]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-history-pagination]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-status]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-task-hint]').isVisible(), false);
    await page.locator('[data-writing-example]').selectOption('ielts-task-1');
    assert.equal(await page.locator('[name=framework]').inputValue(), 'ielts');
    assert.equal(await page.locator('[name=task]').inputValue(), 'ielts_task_1');
    assert.ok((await page.locator('[name=topic]').inputValue()).includes('55%'));
    assert.ok((await page.locator('[name=content]').inputValue()).includes('The table compares'));
    await page.locator('[data-writing-example]').selectOption('ielts-task-2');
    assert.equal(await page.locator('[name=target]').inputValue(), '6.5');
    assert.ok((await page.locator('[name=content]').inputValue()).includes('online learning offer'));
    for (const level of ['a1', 'a2', 'b1', 'b2']) {
        await page.locator('[data-writing-example]').selectOption('cefr-' + level);
        assert.equal(await page.locator('[name=target]').inputValue(), level.toUpperCase());
    }
    await page.locator('[name=content]').fill('');
    assert.ok((await editor.boundingBox()).height <= 100);
    await page.locator('[name=framework]').selectOption('ielts');
    assert.equal(await page.locator('[data-writing-task-hint]').isVisible(), true);
    await page.locator('[name=task]').selectOption('ielts_task_2');
    assert.equal(await page.locator('[data-writing-task-hint]').isVisible(), false);
    await waitText('[data-writing-target]', 'IELTS');
    await page.locator('[name=framework]').selectOption('cefr');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.screenshot({ path: '/tmp/esl1-writing-start-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: '/tmp/esl1-writing-start-unified.png', fullPage: true });
    await page.locator('[name=topic]').fill('Describe a hobby. <script>literal topic</script>');
    await page.locator('[data-writing-create] button[type=submit]').click();
    await page.locator('[data-writing-start]').waitFor({ state: 'hidden' });
    assert.equal((await editor.getAttribute('contenteditable')) === 'true', true);
    assert.ok((await editor.boundingBox()).height >= 220);
    assert.ok((await editor.boundingBox()).height <= 230);
    assert.equal(await page.locator('[data-writing-start]').isVisible(), false);
    const hintToggle = page.locator('[data-writing-hint-toggle]');
    assert.equal(await hintToggle.getAttribute('aria-expanded'), 'false');
    await hintToggle.click();
    assert.equal(await page.locator('[data-writing-prompt-hints]').isVisible(), true);
    assert.equal(await hintToggle.getAttribute('aria-expanded'), 'true');
    await hintToggle.click();
    assert.equal(await page.locator('[data-writing-prompt-hints]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-overall]').textContent(), '—');
    assert.equal(await page.locator('[data-writing-empty]').isVisible(), true);
    await editor.fill('A paragraph to check editor sizing.\n'.repeat(35));
    assert.ok((await editor.boundingBox()).height <= 450);
    assert.ok((await editor.boundingBox()).height > 400);
    assert.ok(await editor.evaluate(el => el.scrollHeight > el.clientHeight));
    await editor.fill('First paragraph.\n\nSecond paragraph.'); await saved();
    assert.ok((await editor.boundingBox()).height <= 230);
    assert.equal(await page.locator('[data-writing-editor-notes]').isVisible(), true);
    const editorCardBox = await page.locator('.tai-writing-editor-card').boundingBox();
    const saveGuideBox = await page.locator('[data-writing-editor-notes]').boundingBox();
    assert.ok(saveGuideBox.y >= editorCardBox.y + editorCardBox.height);

    await page.reload(); await editor.waitFor({ state: 'visible' });
    assert.equal(await editor.innerText(), 'First paragraph.\n\nSecond paragraph.');
    await editor.selectText();
    await page.locator('[data-writing-format=insertUnorderedList]').click();
    assert.ok(await editor.locator('ul').count());
    await editor.evaluate(el => {
        const clipboardData = new DataTransfer();
        clipboardData.setData('text/plain', 'Literal <script>text</script>');
        clipboardData.setData('text/html', '<img src=x onerror=alert(1)>');
        el.dispatchEvent(new ClipboardEvent('paste', { clipboardData, bubbles: true, cancelable: true }));
    });
    assert.equal(await editor.locator('img, script').count(), 0);
    await editor.fill('😀 I likes reading books.'); await saved();
    await editor.selectText();
    await page.locator('[data-writing-format=bold]').click();
    assert.equal(await editor.locator('b, strong').count(), 1);
    await page.locator('[data-writing-expand]').click();
    assert.equal(await page.locator('.tai-writing-editor-card').evaluate(el => el.classList.contains('is-expanded')), true);
    await editor.press('Escape');
    assert.equal(await page.locator('[data-writing-expand]').getAttribute('aria-pressed'), 'false');
    const theme = await page.locator('body').getAttribute('data-ai-tutor-theme');
    await page.locator('[data-tai-theme]').click();
    assert.notEqual(await page.locator('body').getAttribute('data-ai-tutor-theme'), theme);
    assert.equal(await editor.innerText(), '😀 I likes reading books.');
    await page.locator('[data-writing-submit]').click();
    await page.locator('[data-writing-confirm-dialog]').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-writing-confirm-cancel]').evaluate(button => document.activeElement === button), true);
    await page.locator('[data-writing-confirm-cancel]').click();
    assert.equal(posts.length, 0);
    assert.equal(await editor.innerText(), '😀 I likes reading books.');
    await page.locator('[data-writing-submit]').click();
    await page.locator('[data-writing-confirm-dialog]').waitFor({ state: 'visible' });
    await page.keyboard.press('Escape');
    await page.locator('[data-writing-confirm-dialog]').waitFor({ state: 'hidden' });
    assert.equal(posts.length, 0);
    // Abort the response after the mock server accepted a request; recovery must GET, never create a new POST.
    await page.route('**/drafts/*/submit', async route => { await route.fetch(); await route.abort('failed'); });
    await page.locator('[data-writing-submit]').click();
    await page.locator('[data-writing-confirm-accept]').click();
    await page.locator('[data-writing-resume]').waitFor({ state: 'visible' });
    assert.equal(posts.length, 1);
    await page.unroute('**/drafts/*/submit');
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-overall]', '70');
    const stateRoute = '**/writing/submissions/*';
    let mockState = 'queued';
    await page.route(stateRoute, async route => {
        const response = await route.fetch();
        const data = await response.json();
        await route.fulfill({ response, json: { ...data, status: mockState, recovery: 'reconciliation', result: null } });
    });
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-empty-title]', 'Đang chờ đánh giá');
    assert.equal(await page.locator('[data-writing-assessment-progress]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-assessment-progress] [aria-current=step]').textContent(), '2Chờ chấm');
    assert.ok(!(await page.locator('[data-writing-assessment-status]').innerText()).includes('quản trị viên'));
    mockState = 'processing';
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-empty-title]', 'AI đang phân tích');
    assert.equal(await page.locator('[data-writing-assessment-progress] [aria-current=step]').textContent(), '3Phân tích');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: '/tmp/esl1-writing-processing-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: '/tmp/esl1-writing-processing.png', fullPage: true });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    assert.equal(await page.locator('.tai-writing-loading-orbit').evaluate(el => getComputedStyle(el).animationName), 'none');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.unroute(stateRoute);
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-overall]', '70');
    assert.equal(await page.locator('[data-writing-assessment-progress]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-scoreboard]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-tabs]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-result-actions]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-result-actions]').evaluate(el => el.closest('.tai-writing-card') === null), true);
    assert.equal(await page.locator('[data-writing-result-action=submit]').count(), 1);
    assert.equal(await page.locator('[role=meter]').count(), 4);
    assert.equal(await page.locator('[data-writing-issue-count]').textContent(), '1');
    assert.ok((await page.locator('[data-writing-feedback-points=strengths]').textContent()).includes('nêu rõ sở thích'));
    assert.ok((await page.locator('[data-writing-feedback-points=improvements]').textContent()).includes('chia động từ'));
    assert.equal(await page.locator('.tai-writing-ai-feedback h3 svg').count(), 1);
    assert.equal(await page.locator('[data-writing-priorities] li').count(), 2);
    await page.locator('[data-writing-criterion-analysis] summary').click();
    assert.ok((await page.locator('[data-writing-criterion-analysis]').textContent()).includes('Dùng động từ nguyên mẫu'));
    assert.equal(await page.locator('[data-writing-criterion-analysis] script').count(), 0);
    assert.equal(await page.locator('[data-writing-criterion-analysis] blockquote').textContent(), 'likes');
    await page.locator('[data-writing-criterion-analysis] summary').click();
    assert.equal(await page.locator('#tai-writing-feedback-text').evaluate(el => getComputedStyle(el).webkitLineClamp), '2');
    await page.locator('[data-writing-paragraph-analysis] summary').click();
    await page.locator('[data-writing-cefr-target] summary').click();
    assert.ok((await page.locator('[data-writing-cefr-target]').textContent()).includes('CEFR A1'));
    assert.ok((await page.locator('[data-writing-cefr-target]').textContent()).includes('Thể hiện một phần'));
    assert.equal(await page.locator('[data-writing-cefr-target] script').count(), 0);
    assert.equal(await page.locator('[data-writing-cefr-target] blockquote').textContent(), 'reading books');
    await page.locator('[data-writing-cefr-target] summary').click();
    await page.locator('[data-writing-structure] summary').click();
    assert.ok((await page.locator('[data-writing-structure]').textContent()).includes('Ý chính'));
    assert.equal(await page.locator('[data-writing-structure] script').count(), 0);
    assert.equal(await page.locator('[data-writing-structure] blockquote').textContent(), 'reading books');
    await page.locator('[data-writing-structure] summary').click();
    await page.locator('[data-writing-task-check] summary').click();
    assert.ok((await page.locator('[data-writing-task-check]').textContent()).includes('Đã đáp ứng'));
    assert.equal(await page.locator('[data-writing-task-check] script').count(), 0);
    assert.equal(await page.locator('[data-writing-task-check] blockquote').textContent(), 'reading books');
    await page.locator('[data-writing-task-check] summary').click();
    assert.ok((await page.locator('[data-writing-paragraph-analysis]').textContent()).includes('Thêm lý do bạn thích'));
    assert.equal(await page.locator('[data-writing-paragraph-analysis] script').count(), 0);
    assert.equal(await page.locator('[data-writing-paragraph-analysis] blockquote').textContent(), '😀 I likes reading books.');
    await page.locator('[data-writing-paragraph-analysis] summary').click();
    await editor.scrollIntoViewIfNeeded();
    // Autosave/render and polling must preserve explicitly open and closed sections.
    await page.locator('[data-writing-structure] summary').click();
    const preservedText = await editor.innerText();
    await editor.fill(preservedText + ' Temporary edit.');
    assert.equal(await page.locator('[data-writing-structure]').getAttribute('open'), '');
    await editor.fill(preservedText);
    await page.locator('[data-writing-structure] summary').focus();
    await page.locator('[data-writing-refresh]').dispatchEvent('click');
    await page.waitForTimeout(300);
    assert.equal(await page.locator('[data-writing-structure]').getAttribute('open'), '');
    assert.equal(await page.locator('[data-writing-structure] summary').evaluate(el => document.activeElement === el), true);
    await page.locator('[data-writing-structure] summary').click();
    await page.locator('[data-writing-refresh]').click();
    await page.waitForTimeout(300);
    assert.equal(await page.locator('[data-writing-structure]').getAttribute('open'), null);
    await editor.scrollIntoViewIfNeeded();
    await page.waitForTimeout(250);
    const errorRange = await page.evaluate(() => {
        const ranges = [...CSS.highlights.get('tai-writing-grammar')];
        const rect = ranges[0].getBoundingClientRect();
        return { text: ranges[0].toString(), x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 };
    });
    assert.equal(errorRange.text, 'likes');
    await page.mouse.move(errorRange.x, errorRange.y);
    await page.locator('[role=tooltip]').waitFor({ state: 'visible' });
    assert.ok((await page.locator('[role=tooltip]').textContent()).includes('Gợi ý: like'));
    assert.equal(await page.locator('[role=tooltip] script').count(), 0);
    await page.mouse.move(0, 0);
    assert.equal(await page.locator('[role=tooltip]').isVisible(), false);
    await editor.evaluate(el => {
        el.replaceChildren(document.createTextNode('😀 I li'));
        const emphasis = document.createElement('em'); emphasis.textContent = 'kes';
        el.append(emphasis, document.createTextNode(' reading books.'));
    });
    const yellowRoute = /\/writing\/submissions\/[^/?]+$/;
    await page.route(yellowRoute, async route => {
        const response = await route.fetch(); const data = await response.json();
        const start = data.original.indexOf('reading');
        data.result.improvements = ['Hãy kiểm tra cách chia động từ, bổ sung ví dụ cụ thể và liên kết ý rõ ràng hơn. '.repeat(5)];
        data.result.issues.push({ category: 'vocabulary', original: 'reading', replacement: 'reading novels',
            explanation: 'Chọn từ cụ thể hơn. <script>Chỉ là văn bản</script>', start_utf16: start, end_utf16: start + 7, applicable: true });
        await route.fulfill({ response, json: data });
    });
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-issue-count]', '2');
    const improvementsToggle = page.locator('[data-writing-improvements-toggle]');
    await improvementsToggle.waitFor({ state: 'visible' });
    assert.equal(await improvementsToggle.getAttribute('aria-expanded'), 'false');
    assert.equal(await page.locator('#tai-writing-improvements-content').evaluate(el => getComputedStyle(el).webkitLineClamp), '2');
    await improvementsToggle.click();
    assert.equal(await improvementsToggle.getAttribute('aria-expanded'), 'true');
    await improvementsToggle.click();
    await page.locator('[data-writing-result-actions] [data-writing-result-action=improve]').click();
    assert.equal(await improvementsToggle.getAttribute('aria-expanded'), 'true');
    await improvementsToggle.click();
    assert.equal(await page.locator('[data-writing-overview-corrections]').isVisible(), true);
    await page.locator('[data-writing-overview-issue-nav] [data-writing-issue-page=next]').click();
    assert.ok((await page.locator('[data-writing-overview-issues]').textContent()).includes('reading novels'));
    await page.locator('[data-writing-overview-issue-nav] [data-writing-issue-page=prev]').click();
    assert.ok((await page.locator('[data-writing-overview-issues]').textContent()).includes('Dùng I like'));
    await page.locator('[data-writing-tab=details]').click();
    assert.equal(await page.locator('[data-writing-issue-nav] [data-writing-issue-page=prev]').isDisabled(), true);
    await page.locator('[data-writing-issue-nav] [data-writing-issue-page=next]').click();
    assert.ok((await page.locator('[data-writing-issues]').textContent()).includes('reading novels'));
    assert.equal(await page.locator('[data-writing-issue-nav] [data-writing-issue-page=next]').isDisabled(), true);
    await page.locator('[data-writing-issue-nav] [data-writing-issue-page=prev]').click();
    assert.ok((await page.locator('[data-writing-issues]').textContent()).includes('Dùng I like'));
    await page.locator('[data-writing-tab=overview]').click();
    assert.equal(await page.evaluate(() => [...CSS.highlights.get('tai-writing-grammar')][0].toString()), 'likes');
    await editor.scrollIntoViewIfNeeded();
    await page.waitForTimeout(250);
    const yellowRect = await page.evaluate(() => {
        const range = [...CSS.highlights.get('tai-writing-suggestion')][0], rect = range.getBoundingClientRect();
        return { text: range.toString(), x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 };
    });
    assert.equal(yellowRect.text, 'reading');
    await page.mouse.move(yellowRect.x, yellowRect.y);
    await page.locator('[role=tooltip]').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[role=tooltip] script').count(), 0);
    assert.equal(await page.locator('[role=tooltip]').evaluate(el => el.classList.contains('is-grammar')), false);
    await page.unroute(yellowRoute);
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-issue-count]', '1');
    const feedbackToggle = page.locator('[data-writing-feedback-toggle]');
    await feedbackToggle.waitFor({ state: 'visible' });
    assert.equal(await feedbackToggle.getAttribute('aria-expanded'), 'false');
    const collapsedHeight = (await page.locator('#tai-writing-feedback-text').boundingBox()).height;
    await feedbackToggle.click();
    assert.equal(await feedbackToggle.getAttribute('aria-expanded'), 'true');
    assert.ok((await page.locator('#tai-writing-feedback-text').boundingBox()).height > collapsedHeight);
    await page.locator('[data-writing-group=grammar]').click();
    assert.equal(await page.locator('[data-writing-issue-filter=grammar]').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('[data-writing-tab-panel=details]').isVisible(), true);
    assert.equal(await page.locator('[data-writing-result-actions]').isVisible(), true);
    await page.locator('[data-writing-tab=details]').press('ArrowLeft');
    assert.equal(await page.locator('[data-writing-tab=overview]').getAttribute('aria-selected'), 'true');
    assert.equal(await page.locator('[data-writing-tab-panel=details]').isVisible(), false);
    assert.equal(await feedbackToggle.getAttribute('aria-expanded'), 'true');
    await feedbackToggle.click();
    assert.equal(await feedbackToggle.getAttribute('aria-expanded'), 'false');
    await page.evaluate(() => { document.body.dataset.aiTutorTheme = 'light'; });
    await page.screenshot({ path: '/tmp/esl1-writing-ui-light.png', fullPage: true });
    await page.locator('[data-tai-theme]').click();
    assert.equal(await editor.innerText(), '😀 I likes reading books.');
    await page.waitForTimeout(250);
    await page.screenshot({ path: '/tmp/esl1-writing-ui-dark.png', fullPage: true });
    await page.locator('[data-writing-tab=details]').click();
    assert.equal(posts.length, 1); assert.equal(await page.locator('[data-writing-feedback] script').count(), 0);
    assert.equal(await page.locator('[data-writing-original] mark').textContent(), 'likes');
    await page.locator('[data-writing-issues] button').click(); await saved();
    assert.equal(await editor.innerText(), '😀 I like reading books.');
    await page.locator('[data-writing-result-actions] [data-writing-result-action=errors]').click();
    assert.equal(await page.locator('[data-writing-original-panel]').getAttribute('open'), '');
    await page.locator('[data-writing-result-actions] [data-writing-result-action=submit]').click();
    await page.locator('[data-writing-confirm-dialog]').waitFor({ state: 'visible' });
    await page.locator('[data-writing-confirm-cancel]').click();
    assert.equal(posts.length, 1);
    assert.equal(await page.evaluate(() => CSS.highlights.get('tai-writing-grammar')?.size ?? 0), 0);
    assert.equal(await page.locator('[data-writing-tab=details]').getAttribute('aria-selected'), 'true');
    const currentDraftText = await editor.innerText();
    const downloadReport = async () => {
        const pending = page.waitForEvent('download');
        await page.locator('[data-writing-export]').click();
        const download = await pending;
        assert.match(download.suggestedFilename(), /^writing-[\w-]+-v\d+\.txt$/);
        const text = await readFile(await download.path(), 'utf8');
        assert.ok(text.includes('😀 I likes reading books.'));
        assert.ok(!text.includes('😀 I like reading books.'));
        assert.ok(text.includes('70 (thang 100)'));
    };
    await downloadReport();
    await page.locator('[data-writing-history] button').first().click();
    await page.locator('[data-writing-history-view]').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-writing-history] button').first().getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('[data-writing-history] button').first().locator('time').count(), 1);
    assert.equal(await editor.innerText(), '😀 I likes reading books.');
    assert.equal(await editor.getAttribute('contenteditable'), 'false');
    assert.equal(await page.locator('[data-writing-controls]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-issues] button').count(), 0);
    assert.equal(await page.evaluate(() => [...CSS.highlights.get('tai-writing-grammar')][0].toString()), 'likes');
    const historyDraftId = new URL(page.url()).pathname.split('/').at(-1);
    const unchangedDraft = await (await context.request.get(origin + '/ai-tutor/api/v1/writing/drafts/' + historyDraftId)).json();
    assert.equal(unchangedDraft.content, currentDraftText);
    await downloadReport();
    assert.equal(posts.length, 1);
    await page.locator('[data-writing-return-draft]').click();
    assert.equal(await page.locator('[data-writing-history] button[aria-pressed=true]').count(), 0);
    assert.equal(await editor.innerText(), currentDraftText);
    assert.equal(await editor.getAttribute('contenteditable'), 'true');
    await page.reload(); await editor.waitFor({ state: 'visible' });
    assert.equal(await editor.innerText(), '😀 I like reading books.');
    // Missing evidence must stay unscored; an actual zero is still a score.
    const resultRoute = /\/writing\/submissions\/[^/?]+$/;
    await page.route(resultRoute, async route => {
        const response = await route.fetch(); const data = await response.json();
        data.result.overall_score = null; data.result.criteria.grammar.score = null;
        data.result.criteria.vocabulary.score = 0;
        data.result.issues.push({ category: 'coherence', original: data.original, replacement: '',
            explanation: 'General feedback only.', start_utf16: null, end_utf16: null, applicable: false });
        await route.fulfill({ response, json: data });
    });
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-overall]', '—');
    assert.equal(await page.locator('[role=meter]').count(), 3);
    assert.equal(await page.locator('[role=meter][aria-valuenow="0"]').count(), 1);
    assert.equal(await page.locator('[data-writing-empty]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-issues] button').count(), 1);
    await page.locator('[data-writing-tab=details]').click();
    await page.locator('[data-writing-issue-filter=coherence]').click();
    assert.equal(await page.locator('[data-writing-issues] button').count(), 0);
    assert.ok((await page.locator('[data-writing-issues]').textContent()).includes('Nhận xét để bạn tự chỉnh sửa.'));
    await page.unroute(resultRoute);
    // Independent API client simulates a second tab's save.
    await page.route(resultRoute, async route => {
        const response = await route.fetch(); const data = await response.json();
        data.result.score_scale = 'ielts_band_0_9'; data.result.overall_score = 6.5;
        data.rubric = { task: 'ielts_task_1' };
        data.profile = { framework: 'ielts', target: '6.5' }; data.result.cefr_target_analysis = null;
        data.result.criteria = { task_achievement: { score: 6 }, coherence: { score: 6.5 }, vocabulary: { score: 7 }, grammar: { score: 6 } };
        data.result.structure_analysis = [{ component: 'overview', status: 'partial', comment: 'Tổng quan cần rõ hơn.', evidence: ['reading books'], next_step: 'Nêu xu hướng chính.' }];
        data.original += '\n\nOnline online online.';
        data.result.issues.push({ category: 'vocabulary', original: 'reading books', replacement: 'enjoying books',
            explanation: 'Góp ý từ vựng <script>chỉ là text</script>', applicable: false });
        data.comparison = { previous_revision: 1, score_scale: 'ielts_band_0_9', previous_score: 6, current_score: 6.5, overall_delta: 0.5,
            previous_issue_count: 3, current_issue_count: 1, criteria: { grammar: { previous: 5.5, current: 6, delta: 0.5 }, coherence: { previous: 7, current: 6.5, delta: -0.5 } } };
        const observed = { category: 'grammar', original: 'I likes', replacement: 'I like', explanation: 'Chia động từ. <script>chỉ là text</script>' };
        data.comparison.issue_changes = { recurring: { count: 1, items: [observed] },
            not_reported: { count: 1, items: [{ ...observed, original: 'Yesterday I go', original_still_present: false }] },
            newly_reported: { count: 0, items: [] }, unverified_count: 1 };
        await route.fulfill({ response, json: data });
    });
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-overall]', '6.5');
    assert.equal(await page.locator('[data-writing-score-label]').textContent(), 'Band dự kiến');
    assert.equal(await page.locator('[data-writing-cefr-target]').count(), 0);
    assert.ok((await page.locator('[data-writing-task-check]').textContent()).includes('tối thiểu 150'));
    assert.ok((await page.locator('[data-writing-structure]').textContent()).includes('Tổng quan (Overview)'));
    await page.locator('[data-writing-tab=overview]').click();
    await page.locator('[data-writing-vocabulary] summary').click();
    assert.ok((await page.locator('[data-writing-vocabulary]').textContent()).includes('enjoying books'));
    assert.ok((await page.locator('[data-writing-vocabulary]').textContent()).includes('Vị trí chưa xác minh'));
    assert.ok((await page.locator('.tai-writing-vocabulary-frequency').textContent()).includes('online3 lần'));
    assert.equal(await page.locator('[data-writing-vocabulary] script').count(), 0);
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.setViewportSize({ width: 1440, height: 1000 });
    assert.ok((await page.locator('[data-writing-progress]').textContent()).includes('+0.5'));
    assert.ok((await page.locator('[data-writing-progress]').textContent()).includes('-0.5'));
    await page.locator('[data-writing-issue-changes] summary').click();
    assert.ok((await page.locator('[data-writing-issue-changes]').textContent()).includes('AI còn báo lại · 1'));
    assert.ok((await page.locator('[data-writing-issue-changes]').textContent()).includes('chưa xác nhận lỗi đã sửa'));
    assert.equal(await page.locator('[data-writing-issue-changes] script').count(), 0);
    assert.equal(await page.locator('[role=meter][aria-valuemax="9"]').count(), 4);
    assert.ok((await page.locator('[data-writing-criteria]').textContent()).includes('Task Achievement'));
    await page.unroute(resultRoute);
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-score-label]', 'Điểm luyện tập');
    assert.equal(await page.locator('[data-writing-score-label]').textContent(), 'Điểm luyện tập');
    const id = new URL(page.url()).pathname.split('/').at(-1);
    const url = origin + '/ai-tutor/api/v1/writing/drafts/' + id;
    const draft = await (await context.request.get(url)).json();
    await context.request.patch(url, { data: { revision: draft.revision, content: 'Remote tab writes another essay.' } });
    await editor.fill('My current local essay is preserved.');
    await page.locator('[data-writing-conflict]').waitFor({ state: 'visible' });
    assert.equal(await editor.innerText(), 'My current local essay is preserved.');
    await page.locator('[data-writing-keep]').click();
    await page.locator('[data-writing-confirm-accept]').click(); await saved();
    assert.equal(await editor.innerText(), 'My current local essay is preserved.');
    await editor.fill('This mock essay includes /error for a safe failure.'); await saved();
    await page.locator('[data-writing-submit]').click();
    await page.locator('[data-writing-confirm-accept]').click();
    await page.locator('[data-writing-retry]').waitFor({ state: 'visible' });
    await page.locator('[data-writing-retry]').click();
    await page.locator('[data-writing-confirm-accept]').click();
    await waitText('[data-writing-feedback]', 'Mock retry completed');
    assert.ok((await page.locator('[data-writing-cefr-target]').textContent()).includes('chưa có đối chiếu mục tiêu CEFR'));
    assert.ok((await page.locator('[data-writing-vocabulary]').textContent()).includes('chưa có góp ý riêng về từ vựng'));
    assert.ok((await page.locator('[data-writing-structure]').textContent()).includes('Lượt chấm này chưa có phân tích cấu trúc'));
    assert.equal(await feedbackToggle.isVisible(), false);
    assert.equal(posts.length, 3); assert.equal(posts[2].confirm_retry, true);
    assert.notEqual(posts[1].request_id, posts[2].request_id);
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    assert.deepEqual(errors, []);
    await page.screenshot({ path: process.env.AI_PREVIEW_SCREENSHOT ?? '/tmp/esl1-writing-mobile.png', fullPage: true });
    await page.route(resultRoute, async route => {
        const response = await route.fetch(); const data = await response.json();
        data.status = 'failed'; data.error_code = 'AI_CREDIT_INSUFFICIENT'; data.result = null; data.credit_balance = 0;
        await route.fulfill({ response, json: data });
    });
    await page.locator('[data-writing-refresh]').click();
    await page.locator('[data-writing-credit-dialog]').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-writing-credit-close]').evaluate(button => document.activeElement === button), true);
    await page.locator('[data-writing-credit-close]').click();
    await page.locator('[data-writing-refresh]').click();
    await waitText('[data-writing-result-error]', 'Không đủ credit');
    assert.equal(await page.locator('[data-writing-credit-dialog]').isVisible(), false);
    assert.equal(await page.locator('[data-writing-result-error]').isVisible(), true);
    assert.ok((await page.locator('[data-writing-empty-description]').textContent()).includes('bản nháp'));
    assert.ok((await page.locator('[data-writing-credit]').textContent()).includes('Còn lại: 0'));
    await page.unroute(resultRoute);
    // Emulate the available content width beside an LMS sidebar.
    await page.setViewportSize({ width: 1440, height: 1000 });
    const preserved = await editor.innerText();
    await page.locator('[data-tai-writing]').evaluate(root => {
        root.classList.add('tai-writing--embedded');
        root.dataset.aiTutorRoot = ''; root.dataset.aiTutorTheme = 'dark'; root.style.width = '760px';
    });
    const composeBox = await page.locator('.tai-writing-compose').boundingBox();
    const resultsBox = await page.locator('.tai-writing-results').boundingBox();
    assert.ok(Math.abs(composeBox.x - resultsBox.x) < 1, 'Narrow LMS content should stack columns');
    assert.equal(await editor.innerText(), preserved);
    const examplePage = await context.newPage();
    await examplePage.goto(origin + '/writing');
    await examplePage.locator('[data-writing-example]').selectOption('ielts-task-2');
    const initialExample = await examplePage.locator('[name=content]').inputValue();
    await examplePage.locator('[data-writing-create] button[type=submit]').click();
    await examplePage.locator('[data-writing-start]').waitFor({ state: 'hidden' });
    assert.equal(await examplePage.locator('[data-writing-editor]').innerText(), initialExample);
    assert.equal(await examplePage.locator('[data-writing-title]').textContent(), 'IELTS Task 2');
    await examplePage.close();
    console.log('Writing browser smoke passed: examples, autosave, theme, lost-submit recovery, Unicode fixes, reload, two-tab conflict, confirmed retry, mobile and text-only feedback.');
} finally { await browser.close(); }
